# Generated by Django 5.0.1 on 2024-01-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="stripe_customer_id",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
