# Generated by Django 5.0.1 on 2024-01-29 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_product_stock"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
